_wandb:
    value:
        cli_version: 0.23.1
        e:
            7kg21m8o5dfrxylmdv9cwy52rux3hu13:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "510745636864"
                        used: "326545707008"
                email: wubdub23@gmail.com
                executable: C:\GH\scratch\.venv\Scripts\python.exe
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-417cb3bb-bb1d-b324-81f8-17aebfb66045
                host: LAPTOP-KO6MHEAN
                memory:
                    total: "16438304768"
                os: Windows-10-10.0.26100-SP0
                program: C:\GH\scratch\main.py
                python: CPython 3.11.14
                root: C:\GH\scratch
                startedAt: "2025-12-31T04:38:24.162972Z"
                writerId: 7kg21m8o5dfrxylmdv9cwy52rux3hu13
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "8":
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 6
dim:
    value: 10
iterations:
    value: 500
lr:
    value: 0.001
model:
    value: ToyModel
seq_len:
    value: 128
